name: oak
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pandas
  - scipy
  - scikit-learn
  - seaborn
  - tabulate
  - fsspec
  - rich
  - altair
  - plotly
  - bokeh
  - dash
  - solara
  - streamlit
  - shiny
  - shinywidgets
  - nicegui
  - holoviews
  - panel
  - ipython
  - ipywidgets
  - anywidget
  - fastapi
  - voila
  - d3blocks
  - pip
  - pip:
    - py3-wget
    - d3blocks
    - clusteval
    - reflex