name: oak
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - fsspec
  - ipython
  - rich
  - altair
  - plotly
  - bokeh
  - dash
  - streamlit
  - shiny
  - holoviews
  - panel
  - pip
  - pip:
    - py3-wget